name: Push

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Build & test & publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test lib
        run: npm run test:lib:ci
      - name: Build lib
        run: npm run build:lib
      - name: Test demo app
        run: npm run test:app:ci
      - name: Build demo app
        run: npm run build:app
